[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:gateway]
command=dotnet FlowBoard.Gateway.dll --urls "http://0.0.0.0:8080"
directory=/app/gateway
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:auth]
command=dotnet FlowBoard.Auth.dll
environment=ASPNETCORE_URLS="http://*:5048",PORT="",ASPNETCORE_HTTP_PORTS=""
directory=/app/auth
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:workspace]
command=dotnet FlowBoard.Workspace.dll
environment=ASPNETCORE_URLS="http://*:5277",PORT="",ASPNETCORE_HTTP_PORTS=""
directory=/app/workspace
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:board]
command=dotnet FlowBoard.Board.dll
environment=ASPNETCORE_URLS="http://*:5030",PORT="",ASPNETCORE_HTTP_PORTS=""
directory=/app/board
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:list]
command=dotnet FlowBoard.List.dll
environment=ASPNETCORE_URLS="http://*:5266",PORT="",ASPNETCORE_HTTP_PORTS=""
directory=/app/list
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:card]
command=dotnet FlowBoard.Card.dll
environment=ASPNETCORE_URLS="http://*:5024",PORT="",ASPNETCORE_HTTP_PORTS=""
directory=/app/card
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:comment]
command=dotnet FlowBoard.Comment.dll
environment=ASPNETCORE_URLS="http://*:5198",PORT="",ASPNETCORE_HTTP_PORTS=""
directory=/app/comment
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:label]
command=dotnet FlowBoard.Label.dll
environment=ASPNETCORE_URLS="http://*:5027",PORT="",ASPNETCORE_HTTP_PORTS=""
directory=/app/label
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0



