[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:gateway]
command=dotnet FlowBoard.Gateway.dll --urls "http://0.0.0.0:8080"
directory=/app/gateway
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:auth]
command=dotnet FlowBoard.Auth.dll --urls "http://localhost:5048"
directory=/app/auth
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:workspace]
command=dotnet FlowBoard.Workspace.dll --urls "http://localhost:5277"
directory=/app/workspace
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:board]
command=dotnet FlowBoard.Board.dll --urls "http://localhost:5030"
directory=/app/board
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:list]
command=dotnet FlowBoard.List.dll --urls "http://localhost:5266"
directory=/app/list
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:card]
command=dotnet FlowBoard.Card.dll --urls "http://localhost:5024"
directory=/app/card
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:comment]
command=dotnet FlowBoard.Comment.dll --urls "http://localhost:5198"
directory=/app/comment
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:label]
command=dotnet FlowBoard.Label.dll --urls "http://localhost:5027"
directory=/app/label
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
